#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
        echo "This script must be run using sudo!"
        exit 1
fi
docker run -it --name=fsf -d -v ~/fsf-workdir:/home/nonroot/workdir -p 5800:5800 wzod/fsf
